// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJPLsHaUU4sUaSHlIxGaZOsRqiRZc2NZA',
    appId: '1:365527033915:web:65c34b4239fe78e547541e',
    messagingSenderId: '365527033915',
    projectId: 'reels-app-demo-7ec2e',
    authDomain: 'reels-app-demo-7ec2e.firebaseapp.com',
    storageBucket: 'reels-app-demo-7ec2e.firebasestorage.app',
    measurementId: 'G-Z2FT1ESZNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD85v6nFzI-RL9N6aGldhu-sKyvZoJf0ow',
    appId: '1:365527033915:android:941ba67916786b4547541e',
    messagingSenderId: '365527033915',
    projectId: 'reels-app-demo-7ec2e',
    storageBucket: 'reels-app-demo-7ec2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFGVlaiEDKz2DYvH7hJx5sj_-AUpW7jE',
    appId: '1:365527033915:ios:a4ac027769ff48eb47541e',
    messagingSenderId: '365527033915',
    projectId: 'reels-app-demo-7ec2e',
    storageBucket: 'reels-app-demo-7ec2e.firebasestorage.app',
    iosBundleId: 'com.example.reelsAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFGVlaiEDKz2DYvH7hJx5sj_-AUpW7jE',
    appId: '1:365527033915:ios:a4ac027769ff48eb47541e',
    messagingSenderId: '365527033915',
    projectId: 'reels-app-demo-7ec2e',
    storageBucket: 'reels-app-demo-7ec2e.firebasestorage.app',
    iosBundleId: 'com.example.reelsAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJPLsHaUU4sUaSHlIxGaZOsRqiRZc2NZA',
    appId: '1:365527033915:web:3b6c22a97eea390547541e',
    messagingSenderId: '365527033915',
    projectId: 'reels-app-demo-7ec2e',
    authDomain: 'reels-app-demo-7ec2e.firebaseapp.com',
    storageBucket: 'reels-app-demo-7ec2e.firebasestorage.app',
    measurementId: 'G-MFQGZYZGYT',
  );

}